# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform :ios, '10.1'

target 'soundApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for soundApp
  pod 'libpd', :git => 'https://github.com/libpd/libpd', :submodules => true

  target 'soundAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'soundAppUITests' do
    # Pods for testing
  end

end
